[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
via_ir = true
optimizer = true
optimizer_runs = 1
solc = "0.8.30"
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]
fs_permissions = [
    { access = "read-write", path = "./simulation_output" },
]

# Etherscan verification config
[etherscan]
berachain = { key = "${ETHERSCAN_API_KEY}", url = "https://api.berascan.io/api", chain = 80094 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
